/**
 * Movimientos
 */
export const MOVIMIENTOS_RECIBIDOS = 'MOVIMIENTOS_RECIBIDOS';
export const SET_PROPIEDAD_MOVIMIENTO = 'SET_PROPIEDAD_MOVIMIENTO';
export const EDIT_MOVIMIENTO = 'EDIT_MOVIMIENTO';